data:
  raw_dir: "data/raw"
  features_file: "x_train.csv"
  targets_file: "y_train.csv"
  test_features_file: "x_test.csv"
  target_cols: ["fr_spot", "uk_spot"]
  index_col: "datetime_CET"
  splits:
    train_start: "2022-07-01"
    val_start: "2024-05-01"
    test_start: "2024-07-01"

pipeline:
  global_seed: 42

model_settings:
  # Hyperparameter Optimization settings
  hyperopt:
    max_evals: 50
    trials_dir: "data/outputs/trials/"

  # Baseline (LEAR) settings
  lear:
    calibration_window: 56
    
  # Deep Learning Structural Settings (Weights are now in artifact)
  dnn:
    use_data_augmentation: True
    validation_split: 0.2
    top_k_features: 40

  # Ensemble (QRA) Settings
  qra:
    quantiles: [0.05, 0.50, 0.95]
    alpha_winkler: 0.1
    # We keep QRA tree settings hardcoded here as we didn't run Bayesian tuning on the meta-learner
    n_estimators: 500
    learning_rate: 0.05
    num_leaves: 31
    min_child_samples: 20